# Generated by Django 3.2.6 on 2022-01-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_studentschedule_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentschedule',
            name='seat_number',
        ),
        migrations.AlterField(
            model_name='studentschedule',
            name='venue',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
