# Generated by Django 3.2.6 on 2022-01-22 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_venue_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='venue',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.staff')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.venue')),
            ],
        ),
    ]
